FROM --platform=linux/amd64 python:3.11.7-slim-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    sudo \
    # gcc \
    python3-dev \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    libgl1-mesa-glx

COPY ./requirements/* /requirements/
RUN python3 -m pip install --upgrade pip setuptools wheel --no-cache-dir \
    && python3 -m pip install -r requirements/dev.txt --no-cache-dir

ARG DOCK_USER=api

RUN groupadd -g 999 $DOCK_USER \
    && useradd -r -m -u 999 -g $DOCK_USER $DOCK_USER \
    && usermod -a -G sudo $DOCK_USER
USER $DOCK_USER
ENV USER_HOME /home/$DOCK_USER
WORKDIR /home/$DOCK_USER

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["python3 main.py"]
